name: appfridayecommerce
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 6.1.3+402

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  http: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.2.1
  webview_flutter: ^4.0.1
  form_field_validator: ^1.1.0
  photo_view: ^0.14.0
  device_info_plus: ^9.0.3
  substring_highlight: ^1.0.33
  shared_preferences: ^2.0.15
  flutter_carousel_slider: ^1.0.9
  loadmore: ^2.0.1
  shimmer: ^3.0.0
  device_information: ^0.0.4
  # modal_bottom_sheet: ^2.1.2
  modal_bottom_sheet: ^3.0.0-pre
  # platform_device_id: ^1.0.1
  flutter_slidable: ^3.1.1
  flutter_switch: ^0.3.2
  numberpicker: ^2.1.1
  intl: ^0.18.1
  loading_gifs: ^0.3.0
  flutter_share: ^2.0.0
  qr_flutter: ^4.0.0
  rename: ^3.0.2
  firebase_messaging: ^14.7.6
  flutter_local_notifications: ^15.1.1
  overlay_support: ^2.0.1
  firebase_analytics: ^10.7.2
  badges: ^3.1.2
  huawei_push: ^6.5.0+300
  syncfusion_flutter_barcodes: ^22.2.11
  lottie: ^3.1.2
  flutter_staggered_grid_view: ^0.7.0
  firebase_dynamic_links: ^5.4.6
  # flutter_line_sdk: ^2.3.0
  image_network: ^2.5.1
  flutter_native_splash: ^2.2.10
  percent_indicator: ^4.2.2
  flutter_facebook_auth: ^6.0.1
  sign_in_with_apple: ^5.0.0
  share_plus: ^7.1.0
  showcaseview: ^3.0.0
  bouncing_widget: ^2.0.0
  uni_links: ^0.5.1
  flutter_cache_manager: ^3.3.0
  package_info_plus: ^4.1.0
  android_play_install_referrer: ^0.4.0
  mask_text_input_formatter: ^2.4.0
  pin_code_text_field: ^1.8.0
  pin_code_fields: ^8.0.1
  image_gallery_saver: ^2.0.3
  dio: ^5.3.2
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.7
  video_player: ^2.8.2 
  dotted_border: ^2.0.0+2
  chewie: ^1.3.5
  file_picker: ^5.2.1
  flutter_image_compress: ^2.0.4
  flutter_widget_from_html: ^0.15.2
  draggable_fab: ^0.1.4
  carousel_slider: ^5.0.0
  like_button: ^2.0.5
  timeline_tile: ^2.0.0
  webview_flutter_wkwebview: ^3.9.2
  path_provider: ^2.1.1
  expandable_page_view: ^1.0.17
  video_thumbnail: ^0.5.3
  firebase_core: ^2.27.0
  google_sign_in: ^6.2.1
  google_fonts: ^5.1.0
  flutter_branch_sdk: ^7.1.0
  flutter_line_sdk: ^2.5.1
  permission_handler: ^11.3.1
  pub_semver: ^2.1.4
  flutter_svg: ^2.0.10+1
  uuid: ^4.5.1
  connectivity_plus: ^6.0.3
  flutter_fortune_wheel: ^1.3.2
  go_router: ^14.2.3
  socket_io_client: ^3.0.2
  emoji_picker_flutter: ^2.1.1
  web_socket_channel: ^2.4.0
  camera: ^0.10.5+9
  path: ^1.8.3
  photo_manager: ^3.7.1
  cloud_firestore: ^4.15.8
  firebase_database: ^10.4.9
  unique_identifier: ^0.3.0
  transparent_image: ^2.0.1
  url_launcher: ^6.3.0
  external_app_launcher: ^4.0.3
  
# Icon configure
flutter_launcher_icons:
  android: "launcher_icon"
  ios: ture
  image_path: "assets/images/playstore.png"
  remove_alpha_ios: true
  min_sdk_android: 21




dev_dependencies:
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec



# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/language/
    - assets/images/
    - assets/svg/
    - assets/images/menu/
    - assets/images/menu/market/
    - assets/images/logo/
    - assets/images/login/
    - assets/images/profileimg/
    - assets/images/home/
    - assets/images/languages/
    - assets/images/notify/
    - assets/images/cart/
    - assets/images/icon/
    - assets/images/error/
    - assets/images/cartoon/
    - assets/images/flashsale/
    - assets/images/lead/
    - assets/images/live/
    - assets/images/review/
    - assets/images/check_order/
    - assets/images/banner/
    - assets/images/coupon/
    - assets/images/lottie/
    - assets/images/order/
    - assets/images/search/
    - assets/images/b2c/menu/
    - assets/images/b2c/chat/
    - assets/images/b2c/logo/
    - assets/images/b2c/icon/
    - assets/images/b2c/background/
    - assets/images/onboarding/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: notobold
      fonts:
        - asset: fonts/NotoSansThai-Bold.ttf

    - family: noto_medium
      fonts:
        - asset: fonts/NotoSansThai-Medium.ttf


    - family: notoreg
      fonts:
        - asset: fonts/NotoSansThai-Regular.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
