// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnztLwDgSNj80Q0Ot8zLbQkASZhc_-Wp0',
    appId: '1:804780745431:web:68ecda4d6963c78cbbc692',
    messagingSenderId: '804780745431',
    projectId: 'mistineapp',
    authDomain: 'mistineapp.firebaseapp.com',
    storageBucket: 'mistineapp.appspot.com',
    measurementId: 'G-WCRNLC37SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-0BGCzvcekNpbimjEoDnzJvqDYb6m3QM',
    appId: '1:804780745431:android:0defd3fb14910376bbc692',
    messagingSenderId: '804780745431',
    projectId: 'mistineapp',
    storageBucket: 'mistineapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7iMYb1FThG4cYn-qQHg71RJZn9o8fBPg',
    appId: '1:804780745431:ios:8170dac1427645e6bbc692',
    messagingSenderId: '804780745431',
    projectId: 'mistineapp',
    storageBucket: 'mistineapp.appspot.com',
    iosClientId: '804780745431-sbt9pk311aats776crgprcauhas6hpjl.apps.googleusercontent.com',
    iosBundleId: 'com.betterway.yupin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7iMYb1FThG4cYn-qQHg71RJZn9o8fBPg',
    appId: '1:804780745431:ios:0b2c07ce8a277635bbc692',
    messagingSenderId: '804780745431',
    projectId: 'mistineapp',
    storageBucket: 'mistineapp.appspot.com',
    iosBundleId: 'com.example.appfridayecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnztLwDgSNj80Q0Ot8zLbQkASZhc_-Wp0',
    appId: '1:804780745431:web:67e441b292dc3295bbc692',
    messagingSenderId: '804780745431',
    projectId: 'mistineapp',
    authDomain: 'mistineapp.firebaseapp.com',
    storageBucket: 'mistineapp.appspot.com',
    measurementId: 'G-R1TFR7MGEE',
  );
}
