// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhCzOe_waDSU9KhQdbMsxKoQG5sibwXts',
    appId: '1:436932745041:web:350f7524e8eb60b36d2570',
    messagingSenderId: '436932745041',
    projectId: 'friday-online-40aa7',
    authDomain: 'friday-online-40aa7.firebaseapp.com',
    storageBucket: 'friday-online-40aa7.firebasestorage.app',
    measurementId: 'G-HLD6MY8ZKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjvJA2BHkFegQ3saNwwzNuDizw6bjGLIE',
    appId: '1:436932745041:android:ca77bd7efc6a0be26d2570',
    messagingSenderId: '436932745041',
    projectId: 'friday-online-40aa7',
    storageBucket: 'friday-online-40aa7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbnGeT6cZVKfjLmm1oDrLshqhc6zKUJeM',
    appId: '1:436932745041:ios:acd40b2d53799ae36d2570',
    messagingSenderId: '436932745041',
    projectId: 'friday-online-40aa7',
    storageBucket: 'friday-online-40aa7.firebasestorage.app',
    iosBundleId: 'th.co.friday.fridayonline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbnGeT6cZVKfjLmm1oDrLshqhc6zKUJeM',
    appId: '1:436932745041:ios:acd40b2d53799ae36d2570',
    messagingSenderId: '436932745041',
    projectId: 'friday-online-40aa7',
    storageBucket: 'friday-online-40aa7.firebasestorage.app',
    iosBundleId: 'th.co.friday.fridayonline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhCzOe_waDSU9KhQdbMsxKoQG5sibwXts',
    appId: '1:436932745041:web:621a7fcd69214af36d2570',
    messagingSenderId: '436932745041',
    projectId: 'friday-online-40aa7',
    authDomain: 'friday-online-40aa7.firebaseapp.com',
    storageBucket: 'friday-online-40aa7.firebasestorage.app',
    measurementId: 'G-8RLL76LY94',
  );
}
